### ISSUE TITLE
Bar Mash % Display Suggestion

### ISSUE THREAD

**Issue by realblopez** [JCog/fp#21]
I think something that would be useful is to know the exact percentage that you can mash a bar to for things like Power Shock/Dizzy Shell/Spook. Not sure how hard this would be to implement but would be a cool feature.

**Comment by JCog** [comment]
This is actually something that'd be perfect for watches, which will be in the next update. I think along with the update, we'll want to provide a list of some common addresses that people will probably want, such as this one. I made a quick video to demonstrate how it would work: https://www.youtube.com/watch?v=iE5OAGHlh0Q
